MODEL:
  VID:
    ENABLE: True
    METHOD: "cvc_patrans"
    STFT:
      MIN_OFFSET: -9
      MAX_OFFSET: 9
      TRAIN_REF_NUM: 2
      TEST_REF_NUM: 10
    PATRANS:
      MIN_OFFSET: -9
      MAX_OFFSET: 9
      TRAIN_REF_NUM: 2
      TEST_REF_NUM: 10
  META_ARCHITECTURE: "GeneralizedRCNNPATRANS"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RPN_ONLY: True
  FCOS_ON: True
  STFT_ON: True
  BACKBONE:
    CONV_BODY: "R-50-FPN-RETINANET"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
    STAGE_WITH_DCN: (False, True, True, True)
    WITH_MODULATED_DCN: False
    DEFORMABLE_GROUPS: 1
    STAGE_WITH_GCB: (False, True, True, True)
  RETINANET:
    USE_C5: False
  FCOS:
    NUM_CLASSES: 2
    FPN_STRIDES: [8, 16, 32, 64, 128]
    INFERENCE_TH: 0.05
    NMS_TH: 0.6
    PRE_NMS_TOP_N: 1000
    NORM_REG_TARGETS: True
    CENTERNESS_ON_REG: True
    CENTER_SAMPLING_RADIUS: 1.5
    IOU_LOSS_TYPE: "giou"
  STFT:
    OFFSET_WEIGHT_STD: 0.01 
    IOU_THRESH: 0.1 
    BBOX_STD: [0.5, 0.5, 0.5, 0.5]
    REG_BETA: 0.11 
  TRANS:
    PREV_IMG_MODE: "after_ST" # "after_ST" "before_ST"
    SUP_GT_MODE: "align_ltrb_off" # "bbox_pred" "align_ltrb_off"
    MODEL_ENCODER_EMBEDDING_DIM_CLS: 256
    MODEL_ENCODER_EMBEDDING_DIM_REG: 256 
    MODEL_DECODER_INTERMEDIATE_PATRANS: True
    MODEL_SELF_COSPOSITION: True
    MODEL_CROSS_ATT_COSPOSITION: False
    MODEL_SELF_HEADS: 8
    MODEL_ATT_HEADS: 8
    MODEL_PATRANS_NUM: 1
    MODEL_EPSILON: 1e-5
    TRAIN_PATRANS_EMB_DROPOUT: 0.
    TRAIN_PATRANS_DROPPATH: 0.1
    TRAIN_PATRANS_DROPPATH_SCALING: False
    TRAIN_PATRANS_DROPPATH_LST: False
    TRAIN_PATRANS_GLOBAL_DROPOUT: 0.
    TRAIN_PATRANS_LOCAL_DROPOUT: 0.
    PATCH_NUM: 4
    MAX_DIS: 7
    MODEL_MAX_OBJ_NUM: 1
    TRANS_FEAT_LAYER: 2
DATASETS:
  TRAIN: ("ASUVideo_train_videos",)
  TEST: ("ASUVideo_val_videos",) 
INPUT:
  MIN_SIZE_TRAIN: (800,)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.0008
  WEIGHT_DECAY: 0.0001
  IMS_PER_BATCH: 4
  WARMUP_METHOD: "linear"
  WARMUP_ITERS: 500
  CHECKPOINT_PERIOD: 125
  TEST_PERIOD: 125
  MAX_ITER: 6000
  LR_TYPE: "step"
  GAMMA: 0.5
  STEPS: (4000, 5000, 5500)
TEST:
  IMS_PER_BATCH: 4
  DETECTIONS_PER_IMG: 300 
DATALOADER:
  NUM_WORKERS: 4