MODEL:
  VID:
    ENABLE: False
    METHOD: "cvc_image"
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RPN_ONLY: True
  BORDER_ON: True
  BACKBONE:
    CONV_BODY: "R-50-FPN-RETINANET"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
    STAGE_WITH_DCN: (False, True, True, True)
    WITH_MODULATED_DCN: False
    DEFORMABLE_GROUPS: 1
    STAGE_WITH_GCB: (False, True, True, True)
  RETINANET:
    USE_C5: False
  FCOS:
    NUM_CLASSES: 2
    FPN_STRIDES: [8, 16, 32, 64, 128]
    INFERENCE_TH: 0.05
    NMS_TH: 0.6
    PRE_NMS_TOP_N: 1000
    NORM_REG_TARGETS: True
    CENTERNESS_ON_REG: True
    CENTER_SAMPLING_RADIUS: 1.5
    IOU_LOSS_TYPE: "giou"
  BORDER:
    IOU_THRESH: 0.6
    BBOX_STD: [0.5, 0.5, 0.5, 0.5]
DATASETS:
  TRAIN: ("CVCVideo_train_videos",)
  TEST: ("CVCVideo_val_videos",) #2484 frames, subdir in ['2','5','10','18']
INPUT:
  MIN_SIZE_TRAIN: (800,)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  IMS_PER_BATCH: 4
  WARMUP_METHOD: "linear"
  WARMUP_ITERS: 2000
  CHECKPOINT_PERIOD: 500
  TEST_PERIOD: 500
  MAX_ITER: 24000
  LR_TYPE: "step"
  GAMMA: 0.5
  STEPS: (16000, 20000, 22000)
TEST:
  IMS_PER_BATCH: 16
  DETECTIONS_PER_IMG: 300
DATALOADER:
  NUM_WORKERS: 4
