MODEL:
  VID:
    ENABLE: False
    METHOD: "cvc_image"
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RPN_ONLY: True
  FCOS_ON: True
  BACKBONE:
    CONV_BODY: "R-50-FPN-RETINANET"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
    STAGE_WITH_DCN: (False, True, True, True)
    WITH_MODULATED_DCN: False
    DEFORMABLE_GROUPS: 1
    STAGE_WITH_GCB: (False, True, True, True)
  RETINANET:
    USE_C5: False
  FCOS:
    NUM_CLASSES: 2
    FPN_STRIDES: [8, 16, 32, 64, 128]
    INFERENCE_TH: 0.05
    NMS_TH: 0.6
    PRE_NMS_TOP_N: 1000
    NORM_REG_TARGETS: True
    CENTERNESS_ON_REG: True
    CENTER_SAMPLING_RADIUS: 1.5
    IOU_LOSS_TYPE: "giou"
DATASETS:
  TRAIN: ("ASUVideo_train_videos",)
  TEST: ("ASUVideo_val_videos",) #2098 frames, subdir in ['4','24','68','70']
INPUT:
  MIN_SIZE_TRAIN: (800,)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.0005
  WEIGHT_DECAY: 0.0001
  IMS_PER_BATCH: 4
  WARMUP_METHOD: "linear"
  WARMUP_ITERS: 500
  CHECKPOINT_PERIOD: 125
  TEST_PERIOD: 125
  MAX_ITER: 6000
  LR_TYPE: "step"
  GAMMA: 0.5
  STEPS: (4000, 5000, 5500)
TEST:
  IMS_PER_BATCH: 16
  DETECTIONS_PER_IMG: 300
DATALOADER:
  NUM_WORKERS: 4
